# ==============================================================================
#
#               Kustomize Replacements - Strimzi Operator
#
# ==============================================================================
#
# Overview:
#   This file defines the Kustomize `replacements` for the Strimzi Operator
#   Deployment itself.
#
# ==============================================================================

# --- Strimzi Operator Image ---
- source:
    fieldPath: data.images_strimzi_operator_full
    kind: ConfigMap
    name: global-values
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.image
    select:
      kind: Deployment
      name: strimzi-cluster-operator
