# ⚡ Centralized Project Configuration
# ---------------------------------
settings:
  kafka:
    cluster_name: "kafka-cluster"
    version: "4.2.0"
    metadata_version: "4.2-IV0"
    broker_replicas: 1
    controller_replicas: 1
    default_partitions: 6
    port: &kafka_broker_port 9092

  postgres:
    db_name: "postgres"
    user: "postgres"
    password: "postgres"
    port: &postgres_port 5432

  schema_registry:
    port: &sr_port 8081

  kafka_connect:
    port: &kc_port 8083

  redpanda_console:
    port: &rp_port 8080

  cloudbeaver:
    db_name: "cloudbeaver"
    admin_user: "admin"
    admin_password: "admin"
    port: &cb_port 8978

cluster:
  name: "dev-cluster"
  provider: "podman"
  node_image: "kindest/node:v1.31.0"
  ports:
    - name: kafka-broker
      host: *kafka_broker_port
      node: 30092
    - name: postgres
      host: *postgres_port
      node: 30432
    - name: schema-registry
      host: *sr_port
      node: 30081
    - name: kafka-connect
      host: *kc_port
      node: 30083
    - name: redpanda-console
      host: *rp_port
      node: 30080
    - name: cloudbeaver
      host: *cb_port
      node: 30978

images:
  postgres:
    registry: docker.io
    repository: library/postgres
    tag: "17.0-alpine"
  strimzi_operator:
    registry: quay.io
    repository: strimzi/operator
    tag: "0.51.0"
  kafka:
    registry: quay.io
    repository: strimzi/kafka
    tag: "0.51.0-kafka-4.2.0"
  schema_registry:
    registry: quay.io
    repository: apicurio/apicurio-registry-sql
    tag: "2.5.10.Final"
  redpanda_console:
    registry: docker.redpanda.com/redpandadata/console
    tag: "v3.7.1"
  cloudbeaver:
    registry: docker.io
    repository: dbeaver/cloudbeaver
    tag: "26.0.2"
