# ==============================================================================
#
#               Kustomize Overlay - Redpanda Console
#
# ==============================================================================
#
# Overview:
#   This Kustomization file defines the `local` overlay for the Redpanda Console
#   component. It is responsible for packaging the rendered configuration file
#   into a ConfigMap.
#
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    component: redpanda

resources:
  - ../../../base/redpanda

# --- ConfigMap Generator ---
configMapGenerator:
  # Creates the ConfigMap that the base Deployment is configured to mount.
  - name: redpanda-console-config
    files:
      # This syntax renames the file within the ConfigMap's data key.
      # The local file `redpanda-console-config.yaml` (rendered by the Taskfile)
      # will be stored under the key `config.yaml` inside the ConfigMap.
      # This is done because the Redpanda Console pod expects a file named `config.yaml`.
      - config.yaml=redpanda-console-config.yaml
    options:
      labels:
        component: redpanda
