apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    component: redpanda

resources:
  - ../../../base/redpanda

configMapGenerator:
  - name: redpanda-console-config
    files:
      - config.yaml=redpanda-console-config.yaml
    options:
      labels:
        component: redpanda
