# Base: Kafka Controllers
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    component: kafka-nodepool
  includeSelectors: false

resources:
  - nodepool-controller.yaml
