apiVersion: v1
kind: Service
metadata:
  name: rest-proxy
  namespace: infrastructure
  labels:
    component: karapace
spec:
  # EXPOSURE: NodePort allows host-side applications to access the REST Proxy.
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    name: rest
    nodePort: 30082 # This will be replaced by kustomize
  selector:
    app: karapace
