apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    component: cloudbeaver

resources:
  - ../../../base/cloudbeaver

configMapGenerator:
  - name: cloudbeaver-server-config
    files: [cloudbeaver.conf]
    options: {labels: {component: cloudbeaver}}
  - name: cloudbeaver-initial-data-config
    files: [initial-data.conf]
    options: {labels: {component: cloudbeaver}}
  - name: cloudbeaver-global-connections-config
    files: [data-sources.json]
    options: {labels: {component: cloudbeaver}}

patches:
  - path: cloudbeaver.yaml
    target: {kind: Deployment, name: cloudbeaver}
