apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

resources:
  - values.yaml
  - common
  - kafka
  - postgres
  - kafka-connect
  - schema-registry
  - redpanda
  - karapace
  - cloudbeaver

replacements:
  - path: replacements/postgres.yaml
  - path: replacements/kafka.yaml
  - path: replacements/schema-registry.yaml
  - path: replacements/kafka-connect.yaml
  - path: replacements/redpanda.yaml
  - path: replacements/karapace.yaml
  - path: replacements/cloudbeaver.yaml
  - path: replacements/kafka-operator.yaml

labels:
- includeSelectors: false
  pairs:
    env: local
