# ==============================================================================
#
#               OpenTelemetry Collector - ClusterRoleBinding
#
# ==============================================================================
#
# Overview:
#   This manifest defines a `ClusterRoleBinding` that grants the permissions
#   from the `otel-collector` ClusterRole to the `otel-collector` ServiceAccount.
#
#   This allows the OTel Collector pod, which runs as this ServiceAccount, to
#   access the Kubernetes API for enriching telemetry data with Kubernetes metadata.
#
# ==============================================================================

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
  labels:
    component: otel-collector
# `roleRef`: Specifies the role being granted.
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # Refers to the `otel-collector` ClusterRole defined in the other file.
  name: otel-collector
# `subjects`: Specifies who is being granted the role.
subjects:
- kind: ServiceAccount
  # The permissions are granted to the `otel-collector` ServiceAccount...
  name: otel-collector
  # ...which exists in the `infrastructure` namespace.
  namespace: infrastructure
