# ==============================================================================
#
#               Kustomize Overlay - Kafka Connect
#
# ==============================================================================
#
# Overview:
#   This Kustomization file defines the `local` overlay for the Kafka Connect
#   component. Its primary purpose is to include the base manifests and apply a
#   consistent label.
#
#   The actual patching (e.g., setting resource limits, replicas, JVM options)
#   is handled by the `replacements` defined in the top-level
#   `overlays/local/kustomization.yaml`.
#
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds a common label to the KafkaConnect CR and its associated Service.
labels:
- includeSelectors: true
  pairs:
    component: kafka-connect

# Includes the base manifests for Kafka Connect.
resources:
  - ../../../base/kafka-connect
