kafka:
  brokers: ["kafka-cluster-kafka-bootstrap:9092"]
  schemaRegistry:
    enabled: true
    urls: ["http://schema-registry:8081"]
  connect:
    enabled: true
    clusters:
      - name: kafka-connect
        url: "http://kafka-connect:8083"
redpanda:
  adminApi:
    enabled: false
