# ==============================================================================
#
#               Kustomize - Redpanda Console Component
#
# ==============================================================================
#
# Overview:
#   This Kustomization file bundles all the Kubernetes resources required to
#   deploy the Redpanda Console web UI. It acts as a self-contained "component"
#   that is included in the main base aggregator.
#
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ------------------------------------------------------------------------------
# § Component Resources
#   Lists the raw Kubernetes manifests that make up the Redpanda Console component.
# ------------------------------------------------------------------------------
resources:
- deployment.yaml
- service.yaml
